server:
  # 端口
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_redis_simple?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 3s
    lettuce:
      # 关闭超时时间
      shutdown-timeout: 1s
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 4
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 300ms
  cache:
    type: redis
    redis:
      # 过期时间（ms）
      time-to-live: 300_000
      # 缓存null值
      cache-null-values: true

logging:
  root: INFO
  level:
    tk.fishfish: DEBUG